import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Preferences } from '@capacitor/preferences';

export type Lang = 'ar' | 'fr' | 'en' | 'es';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  ar: {
    // Navigation
    home: 'الرئيسية', learn: 'تعلم', assess: 'التقييم', erp: 'ERP',
    journal: 'اليومية', settings: 'الإعدادات', grounding: 'الاسترخاء',
    // Auth
    logout: 'تسجيل الخروج', language: 'اللغة',
    email: 'البريد الإلكتروني', password: 'كلمة المرور',
    loginBtn: 'تسجيل الدخول', registerBtn: 'إنشاء الحساب',
    loginTitle: 'مساعد الوسواس', loginSubtitle: 'أداة دعم نفسي مبنية على أسس علمية',
    registerTitle: 'إنشاء حساب', registerSubtitle: 'ابدأ رحلتك نحو التعافي',
    noAccount: 'ليس لديك حساب؟', createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟', loginLink: 'تسجيل الدخول',
    preferredLang: 'اللغة المفضلة',
    minPasswordError: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    duplicateEmailError: 'البريد الإلكتروني مستخدم بالفعل',
    fillAllFields: 'يرجى تعبئة جميع الحقول',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    // Home
    welcome: 'مرحباً بك', welcomeSub: 'كل خطوة نحو مواجهة الخوف هي انتصار.',
    startHere: 'ابدأ من هنا',
    lastScore: 'آخر تقييم', sessionsWeek: 'إجمالي الجلسات',
    resistanceRate: 'نسبة المقاومة', noDataYet: 'لا توجد بيانات بعد',
    viewHistory: 'عرض السجل', myProgress: 'تقدمي',
    progressChart: 'مسار تقييمات Y-BOCS', progressChartSub: 'تطور درجات الوسواس عبر الزمن',
    ybocs: 'تقييم Y-BOCS', erpSession: 'جلسة ERP',
    thoughtJournal: 'اليومية', learnMore: 'تعلم',
    // Y-BOCS Assessment
    ybocsTitle: 'تقييم Y-BOCS',
    ybocsFormTab: 'التقييم', ybocsHistoryTab: 'السجل',
    obsessionQ: 'أفكار', compulsionQ: 'أفعال', question: 'السؤال',
    totalOf40: 'النتيجة الكلية من 40',
    obsessionScore: 'الأفكار الوسواسية', compulsionScore: 'الأفعال الوسواسية',
    of20: 'من 20',
    selfMonitorNote: 'هذا التقييم للمتابعة الذاتية فقط وليس تشخيصاً طبياً. استشر متخصصاً للتقييم الدقيق.',
    submitAssess: 'عرض النتيجة', newAssessment: 'تقييم جديد',
    noHistory: 'لا توجد تقييمات سابقة',
    ans0: 'لا شيء', ans1: 'خفيف', ans2: 'متوسط', ans3: 'شديد', ans4: 'شديد جداً',
    answeredOf10: 'أسئلة', allAnsweredRequired: 'يرجى الإجابة على جميع الأسئلة',
    sev_subclinical: 'تحت الحد السريري', sev_mild: 'خفيف', sev_moderate: 'متوسط', sev_severe: 'شديد', sev_extreme: 'شديد جداً',
    // ERP Ladder
    fearLadder: 'سلم الخوف', howLadderWorks: 'كيف يعمل سلم الخوف؟',
    ladderDesc: 'أضف المواقف التي تخشاها ورتّبها حسب مستوى القلق (SUDS 0-100). ابدأ بالأقل قلقاً وتدرج نحو الأصعب.',
    noFears: 'لا توجد مواقف بعد', addFearHint: 'اضغط + لإضافة موقف مخيف',
    addFear: 'إضافة موقف', situationPlaceholder: 'صف الموقف المخيف...',
    sudsPlaceholder: 'مستوى القلق (0-100)',
    startSession: 'بدء جلسة', completed: 'مكتمل',
    deleteFearTitle: 'حذف الموقف؟',
    erpRef: 'مبني على بروتوكول ERP — Foa, Yadin & Lichner 2012 · مقياس SUDS — Wolpe 1969',
    // ERP Session
    sessionTitle: 'جلسة ERP', situation: 'الموقف',
    baselineSuds: 'مستوى القلق الأساسي (SUDS)',
    noAnxiety: 'لا قلق', extremeAnxiety: 'قلق شديد جداً',
    startExposure: 'بدء التعرض',
    exposureInfo: 'ستواجه الموقف المخيف دون أي فعل قهري. القلق سيرتفع ثم يتراجع تلقائياً.',
    currentAnxiety: 'مستوى قلقك الآن', habituationCurve: 'منحنى التعود',
    peak: 'الذروة', time: 'الوقت', endExposure: 'إنهاء التعرض',
    before: 'قبل', after: 'بعد', wellDone: 'أحسنت!',
    resistedCompulsion: 'هل قاومت الفعل القهري؟',
    sessionNotes: 'ملاحظات', sessionNotesPlaceholder: 'ما الذي لاحظته خلال الجلسة؟',
    saveSession: 'حفظ الجلسة', sessionSaved: 'تم حفظ الجلسة',
    // Journal
    journalTitle: 'اليومية',
    noRecords: 'لا توجد تسجيلات بعد', addRecordHint: 'اضغط + لتسجيل فكرة اقتحامية',
    addThought: 'تسجيل فكرة', thoughtPlaceholder: 'صف الفكرة الاقتحامية...',
    anxietyPlaceholder: 'مستوى القلق (0-10)', compulsionPlaceholder: 'الفعل الوسواسي (اختياري)',
    resistedLabel: 'مقاومة الفعل ✓', didCompulsion: 'تم الفعل', compulsionLabel: 'الفعل',
    journalRef: 'مبني على نموذج سالكوفسكيس المعرفي 1985 · مبادئ العلاج المعرفي السلوكي',
    // Learn
    learnTitle: 'تعلم', learnBadge: 'محتوى علمي مبني على مصادر موثوقة',
    whatIsOcd: 'ما هو الوسواس القهري؟', whatIsErp: 'ما هو علاج ERP؟',
    ocdTypes: 'أنواع الوسواس القهري', ocdMyths: 'خرافات شائعة عن الوسواس',
    learnOcdBody: 'الوسواس القهري (OCD) اضطراب نفسي يتميز بالأفكار الوسواسية: أفكار متكررة غير مرغوب فيها تسبب قلقاً شديداً. والأفعال القهرية: سلوكيات متكررة للتخفيف من القلق. الفعل القهري يخفف القلق مؤقتاً لكنه يقوّي الوسواس على المدى البعيد.',
    learnOcdBodyStrong1: 'الأفكار الوسواسية:', learnOcdBodyStrong2: 'الأفعال القهرية:', learnOcdBodyStrong3: 'دوامة الوسواس:',
    learnErpBody: 'العلاج بالتعرض ومنع الاستجابة (ERP) هو العلاج الأول موثوقيةً للوسواس القهري. التعرض: مواجهة الموقف المخيف تدريجياً. منع الاستجابة: الامتناع عن الفعل القهري حتى ينخفض القلق من تلقاء نفسه.',
    learnType1: 'التلوث والنظافة', learnType1Sub: 'الخوف من الجراثيم أو النجاسة',
    learnType2: 'الإيذاء', learnType2Sub: 'الخوف من إيذاء النفس أو الآخرين',
    learnType3: 'التناظر والترتيب', learnType3Sub: 'الحاجة للتماثل والكمال',
    learnType4: 'الوسواس الديني', learnType4Sub: 'الشك في الطهارة أو الذنب',
    learnType5: 'الأفكار غير المرغوبة', learnType5Sub: 'أفكار جنسية أو عدوانية مزعجة',
    learnMythWrong: 'خاطئ', learnMythRight: 'صحيح',
    learnMyth1: '«الوسواس يعني أنك شخص سيء» — الأفكار ليست أفعالاً، ولا تعكس شخصيتك.',
    learnMyth2: '«التجاهل يشفي الوسواس» — التجنب يقوّي الوسواس، والمواجهة هي الحل.',
    learnMyth3: '«الوسواس = الاهتمام بالنظافة فقط» — الوسواس له أشكال عديدة.',
    learnFact1: 'الوسواس اضطراب قابل للعلاج بشكل فعّال بـ ERP.',
    learnFact2: 'الأفكار الاقتحامية طبيعية لدى الجميع — ردة الفعل عليها هي المشكلة.',
    // Settings / Profile
    profile: 'الملف الشخصي', changePwd: 'تغيير كلمة المرور',
    currentPwd: 'كلمة المرور الحالية', newPwd: 'كلمة المرور الجديدة',
    confirmPwd: 'تأكيد كلمة المرور', savePwd: 'حفظ',
    pwdMismatch: 'كلمتا المرور غير متطابقتين',
    pwdChanged: 'تم تغيير كلمة المرور بنجاح',
    wrongCurrentPwd: 'كلمة المرور الحالية غير صحيحة',
    exportData: 'تصدير البيانات', exportCSV: 'تصدير CSV',
    aboutApp: 'حول التطبيق', version: 'الإصدار',
    // Grounding
    breathing: 'تمرين التنفس 4-7-8', groundingEx: 'تمرين التأريض 5-4-3-2-1',
    urgeSurfing: 'ركوب موجة الرغبة',
    startExercise: 'ابدأ التمرين', exerciseRunning: 'جارٍ التمرين...',
    exerciseDone: 'أحسنت! اكتمل التمرين.',
    breathingDesc: 'تقنية التنفس الحجافي لتخفيف القلق الفوري.',
    groundingDesc: 'تقنية لإعادة التركيز على اللحظة الحالية عند الشعور بالقلق الشديد.',
    urgeStep1Title: 'لاحظ الرغبة', urgeStep1Sub: 'انتبه إلى الرغبة في الفعل القهري دون محاربتها',
    urgeStep2Title: 'سمّها', urgeStep2Sub: 'هذا يخلق مسافة بينك وبين الفكرة',
    urgeStep3Title: 'ابقَ معها', urgeStep3Sub: 'الموجة ستبلغ ذروتها ثم تتراجع تلقائياً',
    urgeStep4Title: 'راقب التراجع', urgeStep4Sub: 'لاحظ كيف تتضاءل الرغبة دون أن تفعل شيئاً',
    groundingStep1: 'ما الذي تراه؟', groundingStep1Sub: 'انظر حولك وسمّ 5 أشياء تراها',
    groundingStep2: 'ما الذي تلمسه؟', groundingStep2Sub: 'سمّ 4 أشياء يمكنك لمسها',
    groundingStep3: 'ما الذي تسمعه؟', groundingStep3Sub: 'سمّ 3 أصوات تسمعها الآن',
    groundingStep4: 'ما الذي تشمّه؟', groundingStep4Sub: 'سمّ 2 روائح تشمها',
    groundingStep5: 'ما الذي تتذوقه؟', groundingStep5Sub: 'سمّ شيئاً واحداً تتذوقه',
    nextStep: 'التالي', prevStep: 'السابق', startGrounding: 'ابدأ التأريض', resetEx: 'إعادة',
    step: 'الخطوة', of: 'من',
    ybocsRef: 'مقياس ييل-براون للوسواس القهري (Y-BOCS) — Goodman et al. 1989',
    // Common
    save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', yes: 'نعم', no: 'لا',
    error: 'حدث خطأ، حاول مجدداً', success: 'تم بنجاح', loading: 'جارٍ التحميل...',
    // Disclaimer
    disclaimer: 'هذا التطبيق لا يُشكّل تشخيصاً طبياً ولا يُغني عن العلاج المتخصص.',
    disclaimerLogin: 'هذا التطبيق أداة دعم نفسي ولا يُغني عن استشارة متخصص. في حالة الأزمات، تواصل مع طبيب أو معالج نفسي.',
    disclaimerRegister: 'بإنشاء حساب، أنت تقر بأن هذا التطبيق ليس بديلاً عن العلاج المتخصص.',
    dir: 'rtl',
  },
  fr: {
    // Navigation
    home: 'Accueil', learn: 'Apprendre', assess: 'Évaluation', erp: 'ERP',
    journal: 'Journal', settings: 'Paramètres', grounding: 'Relaxation',
    // Auth
    logout: 'Déconnexion', language: 'Langue',
    email: 'Adresse e-mail', password: 'Mot de passe',
    loginBtn: 'Se connecter', registerBtn: 'Créer un compte',
    loginTitle: 'Assistant TOC', loginSubtitle: 'Outil de soutien psychologique fondé sur des preuves scientifiques',
    registerTitle: 'Créer un compte', registerSubtitle: 'Commencez votre chemin vers la guérison',
    noAccount: 'Pas de compte ?', createAccount: 'S\'inscrire',
    alreadyHaveAccount: 'Déjà inscrit ?', loginLink: 'Se connecter',
    preferredLang: 'Langue préférée',
    minPasswordError: 'Le mot de passe doit comporter au moins 6 caractères',
    duplicateEmailError: 'Cet e-mail est déjà utilisé',
    fillAllFields: 'Veuillez remplir tous les champs',
    invalidCredentials: 'E-mail ou mot de passe incorrect',
    // Home
    welcome: 'Bienvenue', welcomeSub: 'Chaque pas vers la confrontation de la peur est une victoire.',
    startHere: 'Commencer ici',
    lastScore: 'Dernière évaluation', sessionsWeek: 'Total des séances',
    resistanceRate: 'Taux de résistance', noDataYet: 'Pas encore de données',
    viewHistory: 'Voir l\'historique', myProgress: 'Ma progression',
    progressChart: 'Suivi Y-BOCS', progressChartSub: 'Évolution de vos scores dans le temps',
    ybocs: 'Évaluation Y-BOCS', erpSession: 'Séance ERP',
    thoughtJournal: 'Journal', learnMore: 'Apprendre',
    // Y-BOCS Assessment
    ybocsTitle: 'Évaluation Y-BOCS',
    ybocsFormTab: 'Évaluation', ybocsHistoryTab: 'Historique',
    obsessionQ: 'Obsessions', compulsionQ: 'Compulsions', question: 'Question',
    totalOf40: 'Score total sur 40',
    obsessionScore: 'Score obsessions', compulsionScore: 'Score compulsions',
    of20: 'sur 20',
    selfMonitorNote: 'Cette évaluation est uniquement pour le suivi personnel, pas un diagnostic médical. Consultez un spécialiste.',
    submitAssess: 'Voir le résultat', newAssessment: 'Nouvelle évaluation',
    noHistory: 'Aucune évaluation précédente',
    ans0: 'Aucun', ans1: 'Léger', ans2: 'Modéré', ans3: 'Sévère', ans4: 'Extrême',
    answeredOf10: 'questions', allAnsweredRequired: 'Veuillez répondre à toutes les questions',
    sev_subclinical: 'Sous le seuil clinique', sev_mild: 'Léger', sev_moderate: 'Modéré', sev_severe: 'Sévère', sev_extreme: 'Extrême',
    // ERP Ladder
    fearLadder: 'Hiérarchie des peurs', howLadderWorks: 'Comment fonctionne la hiérarchie ?',
    ladderDesc: 'Ajoutez les situations que vous craignez et classez-les par niveau d\'anxiété (SUDS 0-100). Commencez par les moins anxiogènes.',
    noFears: 'Aucune situation ajoutée', addFearHint: 'Appuyez sur + pour ajouter une situation',
    addFear: 'Ajouter une situation', situationPlaceholder: 'Décrivez la situation redoutée...',
    sudsPlaceholder: 'Niveau d\'anxiété (0-100)',
    startSession: 'Démarrer séance', completed: 'Terminé',
    deleteFearTitle: 'Supprimer la situation ?',
    erpRef: 'Basé sur le protocole ERP — Foa, Yadin & Lichner 2012 · Échelle SUDS — Wolpe 1969',
    // ERP Session
    sessionTitle: 'Séance ERP', situation: 'Situation',
    baselineSuds: 'Niveau d\'anxiété de base (SUDS)',
    noAnxiety: 'Aucune anxiété', extremeAnxiety: 'Anxiété extrême',
    startExposure: 'Commencer l\'exposition',
    exposureInfo: 'Vous ferez face à la situation redoutée sans acte compulsif. L\'anxiété montera puis diminuera naturellement.',
    currentAnxiety: 'Votre niveau d\'anxiété maintenant', habituationCurve: 'Courbe d\'habituation',
    peak: 'Pic', time: 'Temps', endExposure: 'Terminer l\'exposition',
    before: 'Avant', after: 'Après', wellDone: 'Bravo !',
    resistedCompulsion: 'Avez-vous résisté à la compulsion ?',
    sessionNotes: 'Notes', sessionNotesPlaceholder: 'Qu\'avez-vous observé pendant la séance ?',
    saveSession: 'Enregistrer la séance', sessionSaved: 'Séance enregistrée',
    // Journal
    journalTitle: 'Journal',
    noRecords: 'Aucun enregistrement pour l\'instant', addRecordHint: 'Appuyez sur + pour enregistrer une pensée',
    addThought: 'Enregistrer une pensée', thoughtPlaceholder: 'Décrivez la pensée intrusive...',
    anxietyPlaceholder: 'Niveau d\'anxiété (0-10)', compulsionPlaceholder: 'Acte compulsif (facultatif)',
    resistedLabel: 'Résistance ✓', didCompulsion: 'Compulsion effectuée', compulsionLabel: 'Acte',
    journalRef: 'Basé sur le modèle cognitif de Salkovskis 1985 · Principes TCC — Beck',
    // Learn
    learnTitle: 'Apprendre', learnBadge: 'Contenu scientifique basé sur des sources fiables',
    whatIsOcd: 'Qu\'est-ce que le TOC ?', whatIsErp: 'Qu\'est-ce que le traitement ERP ?',
    ocdTypes: 'Types de TOC', ocdMyths: 'Mythes courants sur le TOC',
    learnOcdBody: 'Le TOC est un trouble psychologique caractérisé par des obsessions : pensées répétitives non désirées causant une anxiété intense. Et des compulsions : comportements répétitifs pour réduire l\'anxiété. La compulsion soulage temporairement mais renforce le TOC à long terme.',
    learnOcdBodyStrong1: 'Obsessions :', learnOcdBodyStrong2: 'Compulsions :', learnOcdBodyStrong3: 'Cycle du TOC :',
    learnErpBody: 'L\'exposition avec prévention de la réponse (ERP) est le traitement de première ligne du TOC. Exposition : confronter progressivement la situation redoutée. Prévention de la réponse : résister à la compulsion jusqu\'à ce que l\'anxiété diminue naturellement.',
    learnType1: 'Contamination / Hygiène', learnType1Sub: 'Peur des germes ou de la saleté',
    learnType2: 'Préjudice', learnType2Sub: 'Peur de se blesser ou de blesser les autres',
    learnType3: 'Symétrie / Ordre', learnType3Sub: 'Besoin de symétrie et de perfection',
    learnType4: 'Scrupules religieux', learnType4Sub: 'Doutes sur la pureté ou la culpabilité',
    learnType5: 'Pensées indésirables', learnType5Sub: 'Pensées sexuelles ou agressives perturbantes',
    learnMythWrong: 'Faux', learnMythRight: 'Vrai',
    learnMyth1: '«Le TOC signifie que vous êtes une mauvaise personne» — Les pensées ne sont pas des actes.',
    learnMyth2: '«Ignorer guérit le TOC» — L\'évitement renforce le TOC, la confrontation est la solution.',
    learnMyth3: '«TOC = obsession de propreté» — Le TOC prend de nombreuses formes.',
    learnFact1: 'Le TOC est un trouble qui se traite efficacement par ERP.',
    learnFact2: 'Les pensées intrusives sont normales chez tout le monde — la réaction est le problème.',
    // Settings / Profile
    profile: 'Profil', changePwd: 'Changer le mot de passe',
    currentPwd: 'Mot de passe actuel', newPwd: 'Nouveau mot de passe',
    confirmPwd: 'Confirmer le mot de passe', savePwd: 'Enregistrer',
    pwdMismatch: 'Les mots de passe ne correspondent pas',
    pwdChanged: 'Mot de passe modifié avec succès',
    wrongCurrentPwd: 'Mot de passe actuel incorrect',
    exportData: 'Exporter les données', exportCSV: 'Exporter CSV',
    aboutApp: 'À propos', version: 'Version',
    // Grounding
    breathing: 'Exercice de respiration 4-7-8', groundingEx: 'Exercice d\'ancrage 5-4-3-2-1',
    urgeSurfing: 'Surfer sur l\'envie',
    startExercise: 'Démarrer l\'exercice', exerciseRunning: 'En cours...',
    exerciseDone: 'Bravo ! Exercice terminé.',
    breathingDesc: 'Technique de respiration pour réduire l\'anxiété immédiatement.',
    groundingDesc: 'Technique pour recentrer sur le moment présent lors d\'une anxiété intense.',
    urgeStep1Title: 'Remarquez', urgeStep1Sub: 'Remarquez l\'envie compulsive sans la combattre',
    urgeStep2Title: 'Nommez-la', urgeStep2Sub: 'Cela crée une distance entre vous et la pensée',
    urgeStep3Title: 'Restez avec elle', urgeStep3Sub: 'La vague atteindra son pic puis diminuera naturellement',
    urgeStep4Title: 'Observez le recul', urgeStep4Sub: 'L\'envie diminue sans que vous fassiez quoi que ce soit',
    groundingStep1: 'Que voyez-vous ?', groundingStep1Sub: 'Regardez autour de vous et nommez 5 choses que vous voyez',
    groundingStep2: 'Que touchez-vous ?', groundingStep2Sub: 'Nommez 4 choses que vous pouvez toucher',
    groundingStep3: 'Qu\'entendez-vous ?', groundingStep3Sub: 'Nommez 3 sons que vous entendez maintenant',
    groundingStep4: 'Que sentez-vous ?', groundingStep4Sub: 'Nommez 2 odeurs que vous sentez',
    groundingStep5: 'Que goûtez-vous ?', groundingStep5Sub: 'Nommez une chose que vous goûtez',
    nextStep: 'Suivant', prevStep: 'Précédent', startGrounding: 'Démarrer', resetEx: 'Recommencer',
    step: 'Étape', of: 'sur',
    ybocsRef: 'Échelle Yale-Brown pour les TOC (Y-BOCS) — Goodman et al. 1989',
    // Common
    save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', yes: 'Oui', no: 'Non',
    error: 'Une erreur s\'est produite', success: 'Succès', loading: 'Chargement...',
    // Disclaimer
    disclaimer: 'Cette application ne remplace pas un diagnostic médical ni un traitement spécialisé.',
    disclaimerLogin: 'Cet outil ne remplace pas une consultation spécialisée. En cas de crise, contactez un médecin ou un thérapeute.',
    disclaimerRegister: 'En créant un compte, vous reconnaissez que cette application n\'est pas un substitut au traitement spécialisé.',
    dir: 'ltr',
  },
  en: {
    // Navigation
    home: 'Home', learn: 'Learn', assess: 'Assess', erp: 'ERP',
    journal: 'Journal', settings: 'Settings', grounding: 'Relax',
    // Auth
    logout: 'Logout', language: 'Language',
    email: 'Email', password: 'Password',
    loginBtn: 'Sign In', registerBtn: 'Create Account',
    loginTitle: 'OCD Helper', loginSubtitle: 'Science-based psychological support tool',
    registerTitle: 'Create Account', registerSubtitle: 'Start your journey toward recovery',
    noAccount: 'Don\'t have an account?', createAccount: 'Sign up',
    alreadyHaveAccount: 'Already have an account?', loginLink: 'Sign in',
    preferredLang: 'Preferred language',
    minPasswordError: 'Password must be at least 6 characters',
    duplicateEmailError: 'This email is already in use',
    fillAllFields: 'Please fill in all fields',
    invalidCredentials: 'Invalid email or password',
    // Home
    welcome: 'Welcome', welcomeSub: 'Every step toward facing fear is a victory.',
    startHere: 'Start here',
    lastScore: 'Last assessment', sessionsWeek: 'Total sessions',
    resistanceRate: 'Resistance rate', noDataYet: 'No data yet',
    viewHistory: 'View history', myProgress: 'My Progress',
    progressChart: 'Y-BOCS Progress', progressChartSub: 'Your score trend over time',
    ybocs: 'Y-BOCS Assessment', erpSession: 'ERP Session',
    thoughtJournal: 'Journal', learnMore: 'Learn',
    // Y-BOCS Assessment
    ybocsTitle: 'Y-BOCS Assessment',
    ybocsFormTab: 'Assessment', ybocsHistoryTab: 'History',
    obsessionQ: 'Obsessions', compulsionQ: 'Compulsions', question: 'Question',
    totalOf40: 'Total score out of 40',
    obsessionScore: 'Obsession score', compulsionScore: 'Compulsion score',
    of20: 'out of 20',
    selfMonitorNote: 'This assessment is for self-monitoring only, not a medical diagnosis. Consult a specialist for accurate evaluation.',
    submitAssess: 'View Result', newAssessment: 'New Assessment',
    noHistory: 'No previous assessments',
    ans0: 'None', ans1: 'Mild', ans2: 'Moderate', ans3: 'Severe', ans4: 'Extreme',
    answeredOf10: 'questions', allAnsweredRequired: 'Please answer all questions',
    sev_subclinical: 'Subclinical', sev_mild: 'Mild', sev_moderate: 'Moderate', sev_severe: 'Severe', sev_extreme: 'Extreme',
    // ERP Ladder
    fearLadder: 'Fear Ladder', howLadderWorks: 'How does the fear ladder work?',
    ladderDesc: 'Add feared situations and rank them by anxiety level (SUDS 0-100). Start with the least anxious and work upward — this is the core of ERP therapy.',
    noFears: 'No situations added yet', addFearHint: 'Tap + to add a feared situation',
    addFear: 'Add situation', situationPlaceholder: 'Describe the feared situation...',
    sudsPlaceholder: 'Anxiety level (0-100)',
    startSession: 'Start session', completed: 'Completed',
    deleteFearTitle: 'Delete situation?',
    erpRef: 'Based on ERP protocol — Foa, Yadin & Lichner 2012 · SUDS scale — Wolpe 1969',
    // ERP Session
    sessionTitle: 'ERP Session', situation: 'Situation',
    baselineSuds: 'Baseline anxiety level (SUDS)',
    noAnxiety: 'No anxiety', extremeAnxiety: 'Extreme anxiety',
    startExposure: 'Start Exposure',
    exposureInfo: 'You will face the feared situation without any compulsive behavior. Anxiety will rise then naturally decrease.',
    currentAnxiety: 'Your current anxiety level', habituationCurve: 'Habituation curve',
    peak: 'Peak', time: 'Time', endExposure: 'End Exposure',
    before: 'Before', after: 'After', wellDone: 'Well done!',
    resistedCompulsion: 'Did you resist the compulsion?',
    sessionNotes: 'Notes', sessionNotesPlaceholder: 'What did you notice during the session?',
    saveSession: 'Save Session', sessionSaved: 'Session saved',
    // Journal
    journalTitle: 'Thought Journal',
    noRecords: 'No records yet', addRecordHint: 'Tap + to record an intrusive thought',
    addThought: 'Record thought', thoughtPlaceholder: 'Describe the intrusive thought...',
    anxietyPlaceholder: 'Anxiety level (0-10)', compulsionPlaceholder: 'Compulsive act (optional)',
    resistedLabel: 'Resisted ✓', didCompulsion: 'Compulsion done', compulsionLabel: 'Act',
    journalRef: 'Based on Salkovskis cognitive model 1985 · CBT principles — Beck',
    // Learn
    learnTitle: 'Learn', learnBadge: 'Science-based content from trusted sources',
    whatIsOcd: 'What is OCD?', whatIsErp: 'What is ERP treatment?',
    ocdTypes: 'Types of OCD', ocdMyths: 'Common myths about OCD',
    learnOcdBody: 'OCD is a psychological disorder characterized by obsessions: repeated unwanted thoughts causing intense anxiety. And compulsions: repetitive behaviors to reduce anxiety. The compulsion temporarily relieves anxiety but reinforces OCD long-term.',
    learnOcdBodyStrong1: 'Obsessions:', learnOcdBodyStrong2: 'Compulsions:', learnOcdBodyStrong3: 'OCD cycle:',
    learnErpBody: 'Exposure and Response Prevention (ERP) is the first-line treatment for OCD. Exposure: gradually confronting the feared situation. Response prevention: resisting the compulsion until anxiety naturally decreases.',
    learnType1: 'Contamination / Cleanliness', learnType1Sub: 'Fear of germs or uncleanliness',
    learnType2: 'Harm', learnType2Sub: 'Fear of harming yourself or others',
    learnType3: 'Symmetry / Order', learnType3Sub: 'Need for symmetry and perfection',
    learnType4: 'Religious scrupulosity', learnType4Sub: 'Doubts about purity or guilt',
    learnType5: 'Unwanted thoughts', learnType5Sub: 'Disturbing sexual or aggressive thoughts',
    learnMythWrong: 'False', learnMythRight: 'True',
    learnMyth1: '"OCD means you are a bad person" — Thoughts are not actions and don\'t reflect your character.',
    learnMyth2: '"Ignoring thoughts cures OCD" — Avoidance strengthens OCD; confrontation is the solution.',
    learnMyth3: '"OCD = obsession with cleanliness" — OCD takes many forms.',
    learnFact1: 'OCD is a disorder that can be treated effectively with ERP.',
    learnFact2: 'Intrusive thoughts are normal for everyone — the reaction to them is the problem.',
    // Settings / Profile
    profile: 'Profile', changePwd: 'Change Password',
    currentPwd: 'Current password', newPwd: 'New password',
    confirmPwd: 'Confirm password', savePwd: 'Save',
    pwdMismatch: 'Passwords do not match',
    pwdChanged: 'Password changed successfully',
    wrongCurrentPwd: 'Current password is incorrect',
    exportData: 'Export data', exportCSV: 'Export CSV',
    aboutApp: 'About', version: 'Version',
    // Grounding
    breathing: '4-7-8 Breathing Exercise', groundingEx: '5-4-3-2-1 Grounding Exercise',
    urgeSurfing: 'Urge Surfing',
    startExercise: 'Start Exercise', exerciseRunning: 'Running...',
    exerciseDone: 'Well done! Exercise complete.',
    breathingDesc: 'Diaphragmatic breathing to immediately reduce anxiety.',
    groundingDesc: 'Technique to refocus on the present moment during intense anxiety.',
    urgeStep1Title: 'Notice', urgeStep1Sub: 'Notice the compulsive urge without fighting it',
    urgeStep2Title: 'Name it', urgeStep2Sub: 'This creates distance between you and the thought',
    urgeStep3Title: 'Ride it out', urgeStep3Sub: 'The wave will peak then naturally fade',
    urgeStep4Title: 'Watch it fade', urgeStep4Sub: 'The urge fades without you needing to act',
    groundingStep1: 'What do you see?', groundingStep1Sub: 'Look around and name 5 things you can see',
    groundingStep2: 'What can you touch?', groundingStep2Sub: 'Name 4 things you can physically touch',
    groundingStep3: 'What do you hear?', groundingStep3Sub: 'Name 3 sounds you can hear right now',
    groundingStep4: 'What do you smell?', groundingStep4Sub: 'Name 2 things you can smell',
    groundingStep5: 'What do you taste?', groundingStep5Sub: 'Name 1 thing you can taste',
    nextStep: 'Next', prevStep: 'Back', startGrounding: 'Start Grounding', resetEx: 'Reset',
    step: 'Step', of: 'of',
    ybocsRef: 'Yale-Brown Obsessive Compulsive Scale (Y-BOCS) — Goodman et al. 1989',
    // Common
    save: 'Save', cancel: 'Cancel', delete: 'Delete', yes: 'Yes', no: 'No',
    error: 'An error occurred', success: 'Success', loading: 'Loading...',
    // Disclaimer
    disclaimer: 'This app does not replace medical diagnosis or specialized treatment.',
    disclaimerLogin: 'This tool does not replace professional consultation. In a crisis, contact a doctor or therapist.',
    disclaimerRegister: 'By creating an account, you acknowledge this app is not a substitute for specialized treatment.',
    dir: 'ltr',
  },
  es: {
    // Navigation
    home: 'Inicio', learn: 'Aprender', assess: 'Evaluación', erp: 'ERP',
    journal: 'Diario', settings: 'Ajustes', grounding: 'Relajación',
    // Auth
    logout: 'Cerrar sesión', language: 'Idioma',
    email: 'Correo electrónico', password: 'Contraseña',
    loginBtn: 'Iniciar sesión', registerBtn: 'Crear cuenta',
    loginTitle: 'Asistente TOC', loginSubtitle: 'Herramienta de apoyo psicológico basada en evidencia científica',
    registerTitle: 'Crear cuenta', registerSubtitle: 'Comienza tu camino hacia la recuperación',
    noAccount: '¿No tienes cuenta?', createAccount: 'Registrarse',
    alreadyHaveAccount: '¿Ya tienes cuenta?', loginLink: 'Iniciar sesión',
    preferredLang: 'Idioma preferido',
    minPasswordError: 'La contraseña debe tener al menos 6 caracteres',
    duplicateEmailError: 'Este correo ya está en uso',
    fillAllFields: 'Por favor completa todos los campos',
    invalidCredentials: 'Correo o contraseña incorrectos',
    // Home
    welcome: 'Bienvenido', welcomeSub: 'Cada paso hacia enfrentar el miedo es una victoria.',
    startHere: 'Empieza aquí',
    lastScore: 'Última evaluación', sessionsWeek: 'Total de sesiones',
    resistanceRate: 'Tasa de resistencia', noDataYet: 'Sin datos aún',
    viewHistory: 'Ver historial', myProgress: 'Mi progreso',
    progressChart: 'Progreso Y-BOCS', progressChartSub: 'Tendencia de tu puntuación en el tiempo',
    ybocs: 'Evaluación Y-BOCS', erpSession: 'Sesión ERP',
    thoughtJournal: 'Diario', learnMore: 'Aprender',
    // Y-BOCS Assessment
    ybocsTitle: 'Evaluación Y-BOCS',
    ybocsFormTab: 'Evaluación', ybocsHistoryTab: 'Historial',
    obsessionQ: 'Obsesiones', compulsionQ: 'Compulsiones', question: 'Pregunta',
    totalOf40: 'Puntuación total sobre 40',
    obsessionScore: 'Puntuación obsesiones', compulsionScore: 'Puntuación compulsiones',
    of20: 'de 20',
    selfMonitorNote: 'Esta evaluación es solo para seguimiento personal, no un diagnóstico médico. Consulta a un especialista.',
    submitAssess: 'Ver resultado', newAssessment: 'Nueva evaluación',
    noHistory: 'Sin evaluaciones previas',
    ans0: 'Ninguno', ans1: 'Leve', ans2: 'Moderado', ans3: 'Severo', ans4: 'Extremo',
    answeredOf10: 'preguntas', allAnsweredRequired: 'Por favor responde todas las preguntas',
    sev_subclinical: 'Subclínico', sev_mild: 'Leve', sev_moderate: 'Moderado', sev_severe: 'Severo', sev_extreme: 'Extremo',
    // ERP Ladder
    fearLadder: 'Escalera del miedo', howLadderWorks: '¿Cómo funciona la escalera del miedo?',
    ladderDesc: 'Agrega situaciones temidas y ordénalas por nivel de ansiedad (SUDS 0-100). Empieza por las menos ansiosas y avanza hacia las más difíciles.',
    noFears: 'Sin situaciones añadidas', addFearHint: 'Toca + para añadir una situación',
    addFear: 'Añadir situación', situationPlaceholder: 'Describe la situación temida...',
    sudsPlaceholder: 'Nivel de ansiedad (0-100)',
    startSession: 'Iniciar sesión', completed: 'Completado',
    deleteFearTitle: '¿Eliminar situación?',
    erpRef: 'Basado en protocolo ERP — Foa, Yadin & Lichner 2012 · Escala SUDS — Wolpe 1969',
    // ERP Session
    sessionTitle: 'Sesión ERP', situation: 'Situación',
    baselineSuds: 'Nivel de ansiedad base (SUDS)',
    noAnxiety: 'Sin ansiedad', extremeAnxiety: 'Ansiedad extrema',
    startExposure: 'Iniciar exposición',
    exposureInfo: 'Enfrentarás la situación temida sin ningún acto compulsivo. La ansiedad subirá y luego disminuirá naturalmente.',
    currentAnxiety: 'Tu nivel de ansiedad ahora', habituationCurve: 'Curva de habituación',
    peak: 'Pico', time: 'Tiempo', endExposure: 'Terminar exposición',
    before: 'Antes', after: 'Después', wellDone: '¡Bien hecho!',
    resistedCompulsion: '¿Resististe la compulsión?',
    sessionNotes: 'Notas', sessionNotesPlaceholder: '¿Qué observaste durante la sesión?',
    saveSession: 'Guardar sesión', sessionSaved: 'Sesión guardada',
    // Journal
    journalTitle: 'Diario de pensamientos',
    noRecords: 'Sin registros aún', addRecordHint: 'Toca + para registrar un pensamiento intrusivo',
    addThought: 'Registrar pensamiento', thoughtPlaceholder: 'Describe el pensamiento intrusivo...',
    anxietyPlaceholder: 'Nivel de ansiedad (0-10)', compulsionPlaceholder: 'Acto compulsivo (opcional)',
    resistedLabel: 'Resistido ✓', didCompulsion: 'Compulsión realizada', compulsionLabel: 'Acto',
    journalRef: 'Basado en modelo cognitivo de Salkovskis 1985 · Principios TCC — Beck',
    // Learn
    learnTitle: 'Aprender', learnBadge: 'Contenido científico basado en fuentes confiables',
    whatIsOcd: '¿Qué es el TOC?', whatIsErp: '¿Qué es el tratamiento ERP?',
    ocdTypes: 'Tipos de TOC', ocdMyths: 'Mitos comunes sobre el TOC',
    learnOcdBody: 'El TOC es un trastorno psicológico caracterizado por obsesiones: pensamientos repetitivos no deseados que causan ansiedad intensa. Y compulsiones: comportamientos repetitivos para reducir la ansiedad. La compulsión alivia temporalmente pero refuerza el TOC a largo plazo.',
    learnOcdBodyStrong1: 'Obsesiones:', learnOcdBodyStrong2: 'Compulsiones:', learnOcdBodyStrong3: 'Ciclo del TOC:',
    learnErpBody: 'La Exposición con Prevención de Respuesta (ERP) es el tratamiento de primera línea del TOC. Exposición: enfrentar progresivamente la situación temida. Prevención de respuesta: resistir la compulsión hasta que la ansiedad disminuya naturalmente.',
    learnType1: 'Contaminación / Limpieza', learnType1Sub: 'Miedo a gérmenes o suciedad',
    learnType2: 'Daño', learnType2Sub: 'Miedo de hacerse daño o dañar a otros',
    learnType3: 'Simetría / Orden', learnType3Sub: 'Necesidad de simetría y perfección',
    learnType4: 'Escrúpulos religiosos', learnType4Sub: 'Dudas sobre pureza o culpabilidad',
    learnType5: 'Pensamientos no deseados', learnType5Sub: 'Pensamientos sexuales o agresivos perturbadores',
    learnMythWrong: 'Falso', learnMythRight: 'Verdadero',
    learnMyth1: '"El TOC significa que eres mala persona" — Los pensamientos no son actos.',
    learnMyth2: '"Ignorar los pensamientos cura el TOC" — Evitar refuerza el TOC; enfrentarlo es la solución.',
    learnMyth3: '"TOC = obsesión por la limpieza" — El TOC tiene muchas formas.',
    learnFact1: 'El TOC es un trastorno que se puede tratar eficazmente con ERP.',
    learnFact2: 'Los pensamientos intrusivos son normales para todos — la reacción a ellos es el problema.',
    // Settings / Profile
    profile: 'Perfil', changePwd: 'Cambiar contraseña',
    currentPwd: 'Contraseña actual', newPwd: 'Nueva contraseña',
    confirmPwd: 'Confirmar contraseña', savePwd: 'Guardar',
    pwdMismatch: 'Las contraseñas no coinciden',
    pwdChanged: 'Contraseña cambiada con éxito',
    wrongCurrentPwd: 'Contraseña actual incorrecta',
    exportData: 'Exportar datos', exportCSV: 'Exportar CSV',
    aboutApp: 'Acerca de', version: 'Versión',
    // Grounding
    breathing: 'Ejercicio de respiración 4-7-8', groundingEx: 'Ejercicio de anclaje 5-4-3-2-1',
    urgeSurfing: 'Surfear el impulso',
    startExercise: 'Iniciar ejercicio', exerciseRunning: 'En curso...',
    exerciseDone: '¡Bien hecho! Ejercicio completado.',
    breathingDesc: 'Respiración diafragmática para reducir la ansiedad de inmediato.',
    groundingDesc: 'Técnica para reenfocarse en el momento presente durante la ansiedad intensa.',
    urgeStep1Title: 'Nota', urgeStep1Sub: 'Nota el impulso compulsivo sin combatirlo',
    urgeStep2Title: 'Nómbralo', urgeStep2Sub: 'Esto crea distancia entre tú y el pensamiento',
    urgeStep3Title: 'Déjalo pasar', urgeStep3Sub: 'La ola alcanzará su pico y luego desaparecerá naturalmente',
    urgeStep4Title: 'Obsérvalo desvanecerse', urgeStep4Sub: 'El impulso se desvanece sin que necesites actuar',
    groundingStep1: '¿Qué ves?', groundingStep1Sub: 'Mira a tu alrededor y nombra 5 cosas que puedes ver',
    groundingStep2: '¿Qué puedes tocar?', groundingStep2Sub: 'Nombra 4 cosas que puedes tocar físicamente',
    groundingStep3: '¿Qué escuchas?', groundingStep3Sub: 'Nombra 3 sonidos que puedes escuchar ahora',
    groundingStep4: '¿Qué hueles?', groundingStep4Sub: 'Nombra 2 cosas que puedes oler',
    groundingStep5: '¿Qué saboreas?', groundingStep5Sub: 'Nombra 1 cosa que puedes saborear',
    nextStep: 'Siguiente', prevStep: 'Anterior', startGrounding: 'Iniciar anclaje', resetEx: 'Reiniciar',
    step: 'Paso', of: 'de',
    ybocsRef: 'Escala Yale-Brown para el TOC (Y-BOCS) — Goodman et al. 1989',
    // Common
    save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', yes: 'Sí', no: 'No',
    error: 'Ocurrió un error', success: 'Éxito', loading: 'Cargando...',
    // Disclaimer
    disclaimer: 'Esta aplicación no reemplaza el diagnóstico médico ni el tratamiento especializado.',
    disclaimerLogin: 'Esta herramienta no reemplaza la consulta profesional. En crisis, contacta a un médico o terapeuta.',
    disclaimerRegister: 'Al crear una cuenta, reconoces que esta aplicación no sustituye el tratamiento especializado.',
    dir: 'ltr',
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private _lang = new BehaviorSubject<Lang>('en');
  lang$ = this._lang.asObservable();

  get current(): Lang { return this._lang.value; }
  get dir(): string { return this.t('dir'); }
  get isRtl(): boolean { return this._lang.value === 'ar'; }
  get supportedLangs(): Lang[] { return ['ar', 'en', 'fr', 'es']; }

  t(key: string): string {
    return TRANSLATIONS[this.current][key] ?? key;
  }

  async init() {
    const { value } = await Preferences.get({ key: 'language' });
    if (value) this._lang.next(value as Lang);
  }

  async setLanguage(lang: Lang) {
    await Preferences.set({ key: 'language', value: lang });
    this._lang.next(lang);
  }
}
